### ISSUE TITLE
Weird utf8 char => bug

### ISSUE THREAD

**Issue by ExtReMLapin** [FPtje/SublimeLinter-contrib-glualint#1]
Code example to be Glua'ed

```Lua
function foo(ohoh)
	print(42)
end


function da(eh)
   	print("∞")
end
```

Error : 

>Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "prettyprint in C:\Users\pierr\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter-contrib-glualint.sublime-package", line 14, in run
  File "prettyprint in C:\Users\pierr\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter-contrib-glualint.sublime-package", line 37, in prettyPrint
  File "./python3.3/subprocess.py", line 920, in communicate
  File "./python3.3/subprocess.py", line 1194, in _communicate
  File "./python3.3/encodings/cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u221e' in position 69: character maps to <undefined>

The infinite utf8 char makes it fail

**Comment by FPtje** [comment]
Works for me in both glualint on Linux and glualint-web. You should probably try to encode it with a different UTF encoding.
